name: Deploy website
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        continue-on-error: true  # Ignore errors

      - name: Lint code
        run: npm run lint
        continue-on-error: true  # Ignore errors

      - name: Test code
        run: npm run test
        continue-on-error: true  # Ignore errors

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        continue-on-error: true  # Ignore errors

      - name: Build website
        run: npm run build
        continue-on-error: true  # Ignore errors

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json
        continue-on-error: true  # Ignore errors

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
        continue-on-error: true  # Ignore errors

      - name: Output contents
        run: ls
        continue-on-error: true  # Ignore errors

      - name: Deploy
        run: echo "Deploying..."
        continue-on-error: true  # Ignore errors
